{% set version = "2.2.2" %}

package:
  name: rio-cogeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rio-cogeo/rio-cogeo-{{ version }}.tar.gz
  sha256: dc574bcb2941fa7e96d1ef1b92e95be625b359f302e3c9edddd793f89b6ed74b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - click
    - morecantile >=2.1,<2.2
    - numpy ~=1.15
    - rasterio >=1.1,<1.2

test:
  imports:
    - rio_cogeo
    - rio_cogeo.scripts
  commands:
    - pip check
    - rio cogeo --help
    - rio cogeo create --help
    - rio cogeo validate --help
  requires:
    - pip
    - boto3 >=1.2.4

about:
  home: https://github.com/cogeotiff/rio-cogeo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CloudOptimized GeoTIFF (COGEO) creation plugin for rasterio

extra:
  recipe-maintainers:
    - ocefpaf
