{% set version = "2.0.1" %}

package:
  name: rio-cogeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rio-cogeo/rio-cogeo-{{ version }}.tar.gz
  sha256: 87cbe02d02b9a2704aeeb509ef49fb6f689020a22fbb4f3ae0d7e292b83a8665

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.3
    - pip
  run:
    - python >3.3
    - click
    - mercantile
    - numpy >=1.15,<2
    - rasterio >=1.0.28
    - supermercado

test:
  imports:
    - rio_cogeo
    - rio_cogeo.scripts
  commands:
    - pip check
    - rio cogeo --help
    - rio cogeo create --help
    - rio cogeo validate --help
  requires:
    - pip
    - boto3 >=1.2.4

about:
  home: https://github.com/cogeotiff/rio-cogeo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CloudOptimized GeoTIFF (COGEO) creation plugin for rasterio

extra:
  recipe-maintainers:
    - ocefpaf
