travis:
  secure:
    BINSTAR_TOKEN: HFwz+StRCv5wkaUQ53/AA4maupNxQM5FJVElxWKOJVfKz2KWZeDiUYr2syTHx7fAR+JP4MesqO3X7gHraAX6RfOGmDUbyQjY8k9SnDXXLPrft+rJU2YSQAqVlURPXgq95Aaicvi89CTxiUlBdM0+15I788te+u1jk5D5wj0SY5RhiDQldCszEc8bM/U3ZoO5NHx5U8zI2Lj1dNSIK1s0VMlNXeUxVB9GKaOgViKbZVu8OoztFFd0ZHoJG+SkSs0Eym/vPs1qEIrzuwUjn/eKZdjS/bvRzaDLB4InR3OMg/jsTuqEU+HUOI55mNbRXZdUAcyGzIsgFIR7nLfPMx3U5XNYuef+wuLigMtSrUJ4d/5oj50oyOKr0y6lAeAaiSHrzJq+Uos4ZKDLojRnG67dR0BC/B7JphIjGmNmtlxiJpw22C3z6P+FmAd5dqUsCHMb3jS/55hZf6dFGrLhxfhiGY29DEnyJJtWMCh6MGniFYhdkigVRrr+GYgO1CKzRZaWxY0dcZmO6dmB2aAJ2OPAASrne73y8OkLtrOG65TozdHhoPAR7/dNjfCXcSls2BQjProjTUDj81XzsGEBZqJmJIBlS+LkB+vStjjIkpDtXlTBiGCKE4tf/Vvn3nnmDQOHOtHn3Ci/2eIuENZASfCDow5buqrSRKg8p1y90d4Qaj0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
